dbfs cp /init/azureconfig.ini dbfs:/init/azureconfig.ini
dbfs cp /init/dateconfig.ini dbfs:/init/dateconfig.ini
dbfs cp /init/database.ini dbfs:/init/database.ini
dbfs cp /init/logconfig.ini dbfs:/init/logconfig.ini
dbfs cp configdirectory.py dbfs:/files/configdirectory.py
dbfs cp tracker.py dbfs:/files/tracker.py
dbfs cp reporter.py dbfs:/files/reporter.py
dbfs cp run_reporter_etl.py dbfs:/files/run_reporter_etl.py
dbfs cp run_data_ingestion.py dbfs:/files/run_data_ingestion.py